# Site settings
title: Disable SSLv3 - a community-powered step-by-step tutorial.
email: rob@twilio.com
description: > # this means to ignore newlines until "baseurl:"
  Learn to disable SSLv3 on your platform, server or client with a step-by-step
  guide created by a community of web users and security professionals. Add
  your guide by contributing to the site's GitHub repository.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://disablesslv3.com" # the base hostname & protocol for your site
scott_label: Scott Helme
scott_link: https://scotthelme.co.uk/
twilio_label: Twilio
twilio_link: https://www.twilio.com
github_link: https://github.com/RobSpectre/disablesslv3 

# Build settings
markdown: kramdown
gems:
  - jemoji
